### ISSUE TITLE
What is the avg_sent_len + 3*std_sent_len for?

### ISSUE THREAD

**Issue by v587su** [yuzhimanhua/HiGitClass#1]
```
	if truncate_sent_len is None:
		truncate_sent_len = min(int(avg_sent_len + 3*std_sent_len), max_sent_len)
```
Hi. I noticed that you set the `truncate_sent_len`  to `avg_sent_len + 3*std_sent_len ` in the code snippet above. The code snippet comes from line 249 in `load_data.py`. Why do you choose this as the minium of the `truncate_sent_len`?

**Comment by yuzhimanhua** [comment]
Hi, Thank you for your interest in our work! 

Here ```avg_sent_len + 3*std_sent_len``` is an analogue of _mean + 3*std_ in normal distribution. We would like to truncate overly long sequences, but do not want to affect most of them. Thus, we believe _mean + 3*std_ is a good choice. You can, of course, set ```max_sent_len``` to other values according to your own data.
